project:
  title: "R-shinylive-demo"
  type: website
  output-dir: _site
  resources: 
  - shinylive-sw.js
  
filters:
  - webr
  - shinylive

website:
  title: "Shinylive und webR Test"
  page-navigation: true
  page-footer:
    right: "[Quarto](https://quarto.org/)"
    left: "Johannes Will, 2024"
  sidebar:
    logo: "images/Logo_Î·_3.png"  
    pinned: false
    align: center
    style: "docked"
    search: true
    collapse-level: 3
    contents:
      - index.qmd
      - text: "VO2-Modellfunktion"
        file: VO2.qmd
      - text: "EPOC-Modellfunktion"
        file: EPOC.qmd
      - text: "Laktat-Leistung"
        file: Laktat.qmd

lang: de
number-sections: true
#bibliography: references.bib
#csl: apa.csl
format:
  html: 
    grid:
      sidebar-width: 250px
      body-width: 1050px
      margin-width: 200px
      gutter-width: 1.5rem
    resources: 
    - shinylive-sw.js
    theme:
      light: [cosmo, theme.scss]  
      dark: [cosmo, theme-dark.scss]
    css: styles.css  
    toc: true
    toc-expand: 3
    toc-title: Inhalt auf dieser Seite
    toc-location: right 
    code-fold: true
    code-tools: true
    code-copy: true
    code-overflow: wrap
    lightbox: true
    #smooth-scroll: true # Macht mit shinylive Probleme